-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
    -   id: autopep8-wrapper
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
