---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Add postgres apt key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add node apt key
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present

    - name: Add PPAs
      apt_repository: repo="{{item}}"
      with_items:
        - "deb https://deb.nodesource.com/node_6.x trusty main"
        - "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install dev tools
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - git
        - python3
        - python3-pip
        - libyaml-dev
    - name: Install build dependencies
      apt: name={{item}} state=build-dep
      register: deps_result
      changed_when: "'will be installed' in deps_result.stdout"
      with_items:
        - python3-pandas
        - python3-numpy
    - name: Install PostgreSQL
      apt: name={{item}} state=present
      with_items:
        - postgresql-9.4
        - postgresql-client-9.4
        - postgresql-contrib-9.4
        - postgresql-server-dev-9.4
        - libpq-dev
        - postgresql-9.4-postgis-2.1
        - postgresql-9.4-postgis-scripts
        - python-psycopg2
    - name: Install Node
      apt: name=nodejs state=latest
    - name: Install webpack
      npm: name=webpack global=yes
    - name: Install sass
      npm: name=node-sass global=yes
    - name: Install babel
      npm: name=babel global=yes
    - name: "Add bashrc"
      template: src=files/bashrc dest=/home/vagrant/.bashrc owner=vagrant
    - name: "pip install"
      pip: executable=pip3 requirements=/vagrant/requirements.txt
    - name: Install Honcho
      pip: executable=pip3 name=honcho
    - name: Configure PostgreSQL
      copy: src=files/postgresql.conf dest=/etc/postgresql/9.4/main/postgresql.conf owner=postgres group=postgres force=yes
      notify:
        - Restart Postgres
    - name: Configure PostgreSQL Auth
      copy: src=files/pg_hba.conf dest=/etc/postgresql/9.4/main/pg_hba.conf owner=postgres group=postgres force=yes
      notify:
        - Restart Postgres
    - name: Install webapp credentials
      copy: src=files/credentials.py dest=/vagrant/cfs/webapp_credentials.py
  handlers:
    - name: Restart Postgres
      service: name=postgresql state=restarted

- hosts: all
  become: yes
  become_method: sudo
  become_user: postgres
  tasks:
    - name: "Create CFS user for Postgres"
      postgresql_user: name=cfs password=cfs role_attr_flags=CREATEDB
    - name: "Create Vagrant user for Postgres"
      postgresql_user: name=vagrant role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER
    - name: "Create PostgreSQL databases"
      postgresql_db: name=cfs owner=cfs state=present
